<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertia.xacro" />


<xacro:property name="draw_bar_length" value="0.03"/>
<xacro:property name="draw_bar_width" value="0.075"/>
<xacro:property name="draw_bar_height" value="0.06"/>

<xacro:property name="rear_chassis_length" value="0.4"/>
<xacro:property name="rear_chassis_width" value="0.13"/>
<xacro:property name="rear_chassis_height" value="0.07"/>

<xacro:property name="bed_length" value="0.46"/>
<xacro:property name="bed_width" value="0.25"/>
<xacro:property name="bed_height" value="0.12"/>

<xacro:property name="wheel_radius" value="0.06"/>
<xacro:property name="wheel_length" value="0.06"/>


<!--DRAW BAR-->
<joint name="base_link_to_draw_bar" type="fixed">
    <parent link="base_link"/>
    <child link="draw_bar"/>
    <origin xyz="-0.11 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.7854" upper="0.7854" velocity="100" effort="100"/>
</joint>

<link name="draw_bar">
    <visual>
        <origin xyz="${-draw_bar_length/2} 0 ${draw_bar_height/2}" rpy="0 0 0"/>
        <geometry>
            <box size="${draw_bar_length} ${draw_bar_width} ${draw_bar_height}"/>
        </geometry>
        <material name="orange"/>
    </visual>
    <collision>
        <origin xyz="${-draw_bar_length/2} 0 ${draw_bar_height/2}" rpy="0 0 0"/>
        <geometry>
            <box size="${draw_bar_length} ${draw_bar_width} ${draw_bar_height}"/>
        </geometry>
        <material name="orange"/>
    </collision>
    <xacro:inertial_box mass="0.1" x="${draw_bar_length}" y="${draw_bar_width}" z="${draw_bar_height}">
        <origin xyz="${-draw_bar_length/2} 0 ${draw_bar_height/2}" rpy="0 0 0"/>
    </xacro:inertial_box>
</link>

<gazebo reference="draw_bar">
    <material>Gazebo/Orange</material>
</gazebo>


<!--REAR CHASSIS-->
<joint name="draw_bar_to_rear_chassis" type="fixed">
    <parent link="draw_bar"/>
    <child link="rear_chassis"/>
    <origin xyz="${-draw_bar_length-rear_chassis_length} 0 0"/>
</joint>

<link name="rear_chassis">
    <visual>
        <origin xyz="${rear_chassis_length/2} 0 ${rear_chassis_height/2}" rpy="0 0 0"/>
        <geometry>
            <box size="${rear_chassis_length} ${rear_chassis_width} ${rear_chassis_height}"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision>
        <origin xyz="${rear_chassis_length/2} 0 ${rear_chassis_height/2}" rpy="0 0 0"/>
        <geometry>
            <box size="${rear_chassis_length} ${rear_chassis_width} ${rear_chassis_height}"/>
        </geometry>
        <material name="blue"/>
    </collision>
    <xacro:inertial_box mass="1" x="${rear_chassis_length}" y="${rear_chassis_width}" z="${rear_chassis_height}">
        <origin xyz="${rear_chassis_length/2} 0 ${rear_chassis_height/2}" rpy="0 0 0"/>
    </xacro:inertial_box>
</link>

<gazebo reference="rear_chassis">
    <material>Gazebo/Blue</material>
</gazebo>


<!--BED-->
<joint name="rear_chassis_to_bed" type="fixed">
    <parent link="rear_chassis"/>
    <child link="bed"/>
    <origin xyz="0 0 ${rear_chassis_height+0.005}"/>
</joint>

<link name="bed">
    <visual>
        <origin xyz="${bed_length/2-0.1} 0 ${bed_height/2}" rpy="0 0 0"/>
        <geometry>
            <box size="${bed_length} ${bed_width} ${bed_height}"/>
        </geometry>
        <material name="blue"/>
    </visual>
    <collision>
        <origin xyz="${bed_length/2+0.1} 0 ${bed_height/2}" rpy="0 0 0"/>
        <geometry>
            <box size="${bed_length} ${bed_width} ${bed_height}"/>
        </geometry>
        <material name="blue"/>
    </collision>
    <xacro:inertial_box mass="0.1" x="${bed_length}" y="${bed_width}" z="${bed_height}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_box>
</link>

<gazebo reference="bed">
    <material>Gazebo/Blue</material>
</gazebo>

<!--REAR AXLE ONE-->
<joint name="draw_bar_to_axle_one" type="fixed">
    <parent link="draw_bar"/>
    <child link="axle_one"/>
    <origin xyz="-0.2 0 0"/>
</joint>

<link name="axle_one">
</link>

<!--REAR WHEEL DRIVE ONE-->
<joint name="axle_one_to_RWD1" type="fixed">
    <parent link="axle_one"/>
    <child link="RWD1"/>
    <origin xyz="0 0 0" rpy="-1.5708 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

<link name="RWD1">
    <visual>
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
    </collision>
    <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
</link>

<gazebo reference="RWD1">
    <material>Gazebo/Black</material>
</gazebo>


<!--LEFT REAR WHEEL ONE-->
<joint name="axle_one_to_LRW1" type="fixed">
    <parent link="axle_one"/>
    <child link="LRW1"/>
    <origin xyz="0 ${rear_chassis_width/2+wheel_length/2+0.005} 0" rpy="-1.5708 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

<link name="LRW1">
    <visual>
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
    </collision>
    <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
</link>

<gazebo reference="LRW1">
    <material>Gazebo/Black</material>
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
</gazebo>


<!--RIGHT REAR WHEEL ONE-->
<joint name="axle_one_to_RRW1" type="fixed">
    <parent link="axle_one"/>
    <child link="RRW1"/>
    <origin xyz="0 ${-rear_chassis_width/2-wheel_length/2-0.005} 0" rpy="1.5708 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

<link name="RRW1">
    <visual>
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
    </collision>
    <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
</link>

<gazebo reference="RRW1">
    <material>Gazebo/Black</material>
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
</gazebo>


<!--REAR AXLE TWO-->
<joint name="axle_one_to_axle_two" type="fixed">
    <parent link="axle_one"/>
    <child link="axle_two"/>
    <origin xyz="-0.15 0 0"/>
</joint>

<link name="axle_two">
</link>


<!--REAR WWEEL DRIVE TWO-->
<joint name="axle_two_to_RWD2" type="fixed">
    <parent link="axle_two"/>
    <child link="RWD2"/>
    <origin xyz="0 0 0" rpy="-1.5708 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

<link name="RWD2">
    <visual>
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
    </collision>
    <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
</link>

<gazebo reference="RWD2">
    <material>Gazebo/Black</material>
</gazebo>

<!--LEFT REAR WHEEL TWO-->
<joint name="axle_two_to_LRW2" type="fixed">
    <parent link="axle_two"/>
    <child link="LRW2"/>
    <origin xyz="0 ${rear_chassis_width/2+wheel_length/2+0.005} 0" rpy="-1.5708 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

<link name="LRW2">
    <visual>
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
    </collision>
    <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
</link>

<gazebo reference="LRW2">
    <material>Gazebo/Black</material>
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
</gazebo>


<!--RIGHT REAR WHEEL TWO-->
<joint name="axle_two_to_RRW2" type="continuous">
    <parent link="axle_two"/>
    <child link="RRW2"/>
    <origin xyz="0 ${-rear_chassis_width/2-wheel_length/2-0.005} 0" rpy="1.5708 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

<link name="RRW2">
    <visual>
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
    </visual>
    <collision>
        <geometry>
            <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
    </collision>
    <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
</link>

<gazebo reference="RRW2">
    <material>Gazebo/Black</material>
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
</gazebo>

</robot>